### PR TITLE
Fixing status update in UploadRequest records.

### LINKED ISSUE #24: Status update and Files deletion not working after successful upload
After Successful upload of PPG video and image data to minIO blob storage, Zip files should be deleted from local storage to free space & Status should be updated to success in ResourceInfo, CameraInfo & UploadRequest Entities in room storage , but instead it remains Pending!
Due to this it retries uploading again while syncing next time and gives FileNotFound Exception.

@MJ1998

### PR DESCRIPTION
**Pull request by MJ1998**
Fixes #24 

We make use of an API already there: `insertUploadRequest` by setting onConflict strategy to REPLACE. This will check for the presence of the record and, if found, update the old value with new values.

TESTED=
Screenshot 2023-11-20 at 20 53 26

### CODE REVIEW

File: sensing/src/main/java/com/google/android/sensing/db/impl/DatabaseImpl.kt [hunk 1]
```diff
@@ -67,7 +67,7 @@ internal class DatabaseImpl(context: Context, databaseConfig: DatabaseConfig) :
   }
 
   override suspend fun updateUploadRequest(uploadRequest: UploadRequest) {
-    uploadRequestDao.updateUploadRequest(uploadRequest)
+    uploadRequestDao.insertUploadRequest(uploadRequest)
```
Comment (chandrashekar-s) [inline sensing/src/main/java/com/google/android/sensing/db/impl/DatabaseImpl.kt:70]: Just wondering why the record needs to re-inserted on upload? Also, I was found that the `id` is set to `0` during `update` transaction here. Can you please check this?

Comment (MJ1998) [reply sensing/src/main/java/com/google/android/sensing/db/impl/DatabaseImpl.kt:70]: Record is being updated using the same insert API with onConflict strategy being repace.

Internally it checks for primary key or alternate unique key. If founf replaces old values with new values.

The id = 0 is not wrong. 
If you go to the definition of id you will see its an AutoGenerate parameter

Comment (MJ1998) [reply sensing/src/main/java/com/google/android/sensing/db/impl/DatabaseImpl.kt:70]: This onConflict = REPLACE strategy is inspired from Android FHIR SDK but it seems that they use it to write clean and precise code ([ref](https://github.com/google/android-fhir/blob/76ecd8c746b17b2297241683516a100812a5dbe2/engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt#L117-L121
))

Currently we are going to stick to this code as the same strategy is being used in other entities but we can make improvements. Check this [issue](https://github.com/google-research/CVD-paper-mobile-camera-example/issues/39)

Comment (chandrashekar-s) [reply sensing/src/main/java/com/google/android/sensing/db/impl/DatabaseImpl.kt:70]: This sounds fine, thanks @MJ1998 for creating the [issue](https://github.com/google-research/CVD-paper-mobile-camera-example/issues/39) to track for optimisations

**Review by chandrashekar-s — APPROVED** [review]
