### PR TITLE
Optimizing synchronization: release lock in finally block, synchronize block in the same coroutine

### LINKED ISSUE #58: sync lock is not released if it encounters an exception

### PR DESCRIPTION
**Pull request by MJ1998**
Fixes #58 and #55 

Changes Made:
1. Removal of the separate coroutine launch for synchronization, leveraging the finite emit cold flow from synchronize().
2. Introducing a try-catch-finally block around synchronize() to handle exceptions.
3. Increasing the connection timeout to 30 seconds to address ConnectTimeoutException occurrences.

Positive side effect: elimination of the need for an additional coroutine for collecting SyncUploadStates.

Testing:
Network connection was deliberately shut off to observe the behavior during ConnectTimeoutException.
The lock is successfully released, and the worker returns Result.retry.
Successfully observe last set progress from both periodic and one time sync workers.

### CODE REVIEW

File: sensing/src/main/java/com/google/android/sensing/upload/SensorDataUploadWorker.kt [hunk 1]
```diff
@@ -59,39 +55,41 @@ class SensorDataUploadWorker(appContext: Context, workerParams: WorkerParameters
   }
 
   override suspend fun doWork(): Result {
+    if (runAttemptCount == inputData.getInt(MAX_RETRIES_ALLOWED, 0)) return Result.failure()
```
Comment (chandrashekar-s) [inline sensing/src/main/java/com/google/android/sensing/upload/SensorDataUploadWorker.kt:58]: nit: Should we make it something like `runAttemptCount >= inputData.getInt(MAX_RETRIES_ALLOWED, 0)` to be on a safer side?

**Review by chandrashekar-s — APPROVED** [review]
The changes look fine, there is one minor comment. You can have a look.
